### ISSUE TITLE
bitwig + launchcontrol xl

### ISSUE THREAD

**Issue by jojolaricot** [jdachtera/bitwig-novation-launch-control-xl#1]
Very good script!!!! Not possible control select vst (launchcontrol xl: device select) for parametre vst (filtre,rez,attak,decay,............) style ableton...?

**Comment by jdachtera** [comment]
This is a limitation of Bitwig. You have to map the parameter pages yourself. Click on the gearwheel symbol at left lower corner of the vst device in bitwig. Then add a new parameter page by click on the plus button at the top. Now drag the 8 parameters onto the knobs you want to map. Proceed by adding more pages until all knobs are mapped.
![bildschirmfoto 2015-01-11 um 12 37 22](https://cloud.githubusercontent.com/assets/980740/5695083/f7138142-998e-11e4-9d7a-29b826f55114.png)
