### ISSUE TITLE
README needs set-up instructions

### ISSUE THREAD

**Issue by travenasty** [jdachtera/bitwig-novation-launch-control-xl#2]
There is a mountain of beautiful code here that I am unable to figure out how to run. I am unaware of what dependency I am missing, and my google skills seem to be lacking to find anything helpful.  Why are the require statements using an undefined 'load' function, do I need to npm install something?  A few lines in the README explaining where to start or adding a package.json to declare/install package dependencies, that would be fantastic.

**Comment by jdachtera** [comment]
This code needs to be run inside of http://www.bitwig.com/en/bitwig-studio.html. It provides the global load function. If you don't use the software then it probably won't be useful to you. If you do you might want to look at the api https://github.com/trappar/bitwig-api-stubs. Anyway I agree: Yes there should ideally be some description.

**Comment by travenasty** [comment]
Ah! perfect.  Thank you for the quick response.
