### ISSUE TITLE
Bitwig 2.0

### ISSUE THREAD

**Issue by dcupmusic** [jdachtera/bitwig-novation-launch-control-xl#7]
Hi Jascha 

I love this script.
Sadly its doesnt seem to be compatible with BW2.0

Will you be updating it? 

I struggled for months to make a basic script for the akai midimix, and now that doesnt work either :(

Many thanks
Dunan

**Comment by NexxtDK** [comment]
Hi Jascha

I love your script too and will answer if you can update or if you plan to update your sript for Bitwig 2.0

Thanks a lot
David

**Comment by NexxtDK** [comment]
Got it to work for me.
Im on MAC
I got this error code 
<img width="384" alt="bildschirmfoto 2017-04-14 um 08 45 41" src="https://cloud.githubusercontent.com/assets/27445658/25035692/62c3a6c6-20ef-11e7-94aa-14b16a8dd852.png">

To fix it, go to the file LaunchControlXL.js on your directorie (Bitwig ControllerScript folder) open it with TextEdit or a similar app. Search for the Line 
.on('double tap', this.application.toggleDevices.bind(this.application));
end delete it.    
Hope it will work for you.
kind regards
David

**Comment by jdachtera** [comment]
Hi @dcupmusic & @NexxtDK,
Thanks for using the script :)
I had a look and committed a fix for this issue. If you just delete the line the switching of the device section won't work anymore.
Kind Regards,
Jascha
